[mcp_servers.supabase]
type = "command"
command = "pnpm"
args = ["exec", "mcp-server-supabase", "--project-ref=qqewusetilxxfvfkmsed", "--service-role-key-auth"]
[mcp_servers.supabase.env]
SUPABASE_SERVICE_ROLE_KEY = "${SUPABASE_SERVICE_ROLE_KEY}"
